var projectilesData = {
	fire : {
		sheet:{
			start:{
				path:"images/battle/projectileSheets/start_fire.png",
				frameWidth:200,
				frameHeight:200,
				frameMax:11,
				fps:12
			},
			idle:{
				path:"images/battle/projectileSheets/idle_fire.png",
				frameWidth:200,
				frameHeight:200,
				frameMax:11,
				fps:12
			}
		},
		"impact":{
			"particles":[
				"images/battle/particles/Fire/rock2a.png"
			],
			"soundID":"epicFireExplosion1"
		},
	},
	water : {
		sheet:{
			start:{
				path:"images/battle/projectileSheets/start_water.png",
				frameWidth:140,
				frameHeight:140,
				frameMax:24,
				fps:24
			},
			idle:{
				path:"images/battle/projectileSheets/idle_water.png",
				frameWidth:140,
				frameHeight:140,
				frameMax:24,
				fps:24
			}
		},
		"impact":{
			"particles":[
				"images/battle/particles/Water&Ice/shell1.png"
			],
			"soundID":"epicImpactWater1"
		},
	},
	earth : {
		sheet:{
			start:{
				path:"images/battle/projectileSheets/start_earth.png",
				frameWidth:200,
				frameHeight:200,
				frameMax:25,
				fps:24
			},
			idle:{
				path:"images/battle/projectileSheets/idle_earth.png",
				frameWidth:200,
				frameHeight:200,
				frameMax:25,
				fps:24
			}
		},
		"impact":{
			"particles":[
				"images/battle/particles/Earth/stone1.png"
			],
			"soundID":"epicEarthImpact1"
		},

	},
	wind : {
		sheet:{
			start:{
				path:"images/battle/projectileSheets/start_wind.png",
				frameWidth:140,
				frameHeight:140,
				frameMax:24,
				fps:24
			},
			idle:{
				path:"images/battle/projectileSheets/idle_wind.png",
				frameWidth:140,
				frameHeight:140,
				frameMax:26,
				fps:24
			}
		},
		"impact":{
			"particles":[
				"images/battle/particles/Wind/cloud1.png"
			],
			"soundID":"epicWindImpact1"
		},
	}
}