var yogomeGames = {}
yogomeGames.getGames = function(){
	var games = [

		{
            name:'additionDojo',
            url:'games/nonrefactored/additionDojo/additionDojo',
            sceneName:'dojo',
            subject:'math',
            review:true
        },
        {
            name:'spaceWords',
            url:'games/nonrefactored/spaceWords/spaceWords',
            sceneName:'space',
            subject:'language',
            review:true
        },
        {
            name:'mathRun',
            url:'games/nonrefactored/mathRun/mathRun',
            sceneName:'runneryogome',
            subject:'math',
            review:true
        },        
        {
            name:'waterMorphosis',
            url:'games/nonrefactored/waterMorphosis/waterMorphosis',
            sceneName:'water',
            subject:'science',review:true},
		{
            name:'numberIceCream',
            url:'games/nonrefactored/numberIceCream/numberIceCream',
            sceneName:'ice',
            subject:'math',
            review:true
        },{
            name:'magnetRide',
            url:'games/nonrefactored/magnetRide/magnetRide',
            sceneName:'magnet',
            subject:'science',
            review:true
        },
		{
            name:'saladCards',
            url:'games/nonrefactored/saladCards/saladCards',
            sceneName:'tapcards',
            subject:'language',
            review:true
        },
		{
            name:'skyLanguage',
            url:'games/nonrefactored/skyLanguage/skyLanguage',
            sceneName:'sky',
            subject:'language',
            review:true
        },
		{
            name:'flagRunner',
            url:'games/nonrefactored/flagRunner/flagRunner',
            sceneName:'flag',
            subject:'geography',
            review:true
        },
		{
            name:'riftLand',
            url:'games/nonrefactored/riftLand/riftLand',
            sceneName:'rift',
            subject:'coding',
            review:true
        },
		{
            name:'puzzleRoad',
            url:'games/nonrefactored/puzzleRoad/puzzleRoad',
            sceneName:'puzzle',
            subject:'creativity',
            review:true
        },
		{
            name:'geoJourney',
            url:'games/nonrefactored/geoJourney/geoJourney',
            sceneName:'geoJourney',
            subject:'geography',
            review:true
        },
		{
            name:'memoNumbers',
            url:'games/nonrefactored/memoNumbers/memoNumbers',
            sceneName:'memo',
            subject:'math',
            review:true
        },
		{
            name:'beachNinja',
            url:'games/nonrefactored/beachNinja/beachNinja',
            sceneName:'beach',
            subject:'math',
            review:true
        },
        {
            name:'flyingFractions',
            url:'games/nonrefactored/flyingFractions/flyingFractions',
            sceneName:'flyingFractions',
            subject:'math',
            review:true
        },
		{
            name:'colorAttack',
            url:'games/nonrefactored/colorAttack/colorAttack',
            sceneName:'color',
            subject:'creativity',
            review:true
        },
		{
            name:'nutriCanon',
            url:'games/nonrefactored/nutriCanon/nutriCanon',
            sceneName:'nutri',
            subject:'health',
            review:true
        },
		{
            name:'microdefender',
            url:'games/nonrefactored/microdefender/microdefender',
            sceneName:'microdefender',
            subject:'health',
            review:true
        },
		{
            name:'healthyCollector',
            url:'games/nonrefactored/healthyCollector/healthyCollector',
            sceneName:'healthyCollector',
            subject:'health',
            review:true
        },
        {
            name:'CroakSong',
            url:'games/nonrefactored/CroakSong/CroakSong',
            sceneName:'CroakSong',
            subject:'creativity',
            review:true
        },
		{
            name:'tiltSprout',
            url:'games/nonrefactored/tiltSprout/tiltSprout',
            sceneName:'tilt',
            subject:'science',
            review:true
        },
		{
            name:'cultureIcons',
            url:'games/nonrefactored/cultureIcons/cultureIcons',
            sceneName:'culture',
            subject:'geography',
            review:true
        },
		{
            name:'dizzyBoat',
            url:'games/nonrefactored/dizzyBoat/dizzyBoat',
            sceneName:'dizzy',
            subject:'geography',
            review:true
        },
		{
            name:'flagCollector',
            url:'games/nonrefactored/flagCollector/flagCollector',
            sceneName:'flag',
            subject:'geography',
            review:true
        },
		{
            name:'mediCatcher',
            url:'games/nonrefactored/mediCatcher/mediCatcher',
            sceneName:'medi',
            subject:'health',
            review:true
        },
        {
            name:'wildSnaps',
            url:'games/nonrefactored/wildSnaps/wildSnaps',
            sceneName:'wild',
            subject:'creativity',
            review:true
        },
		{
            name:'geMath',
            url:'games/nonrefactored/geMath/geMath',
            sceneName:'gem',
            subject:'math',
            review:true
        },
		{
            name:'hackaMole',
            url:'games/nonrefactored/hackaMole/hackaMole',
            sceneName:'hack',
            subject:'coding',
            review:true
        },		
		{
            name:'lizart',
            url:'games/nonrefactored/lizart/lizart',
            sceneName:'lizart',
            subject:'language',
            review:true
        },
		{
            name:'snoozeCrater',
            url:'games/nonrefactored/snoozeCrater/snoozeCrater',
            sceneName:'snooze',
            subject:'health',
            review:true
        },//29
		{
            name:'mathFeed',
            url:'games/nonrefactored/mathFeed/mathFeed',
            sceneName:'feed',
            subject:'math',
            review:true
        },//30
		{
            name:'galaxyHeroes',
            url:'games/nonrefactored/galaxyHeroes/galaxyHeroes',
            sceneName:'galaxy',
            subject:'geography',
            review:true
        },//31
		{
            name:'popFish',
            url:'games/nonrefactored/popFish/popFish',
            sceneName:'fish',
            subject:'math',
            review:true
        },//32
        {
            name:'bouncybath',
            url:'games/nonrefactored/bouncybath/bouncybath',
            sceneName:'bouncybath',
            subject:'health',
            review:false
        },//33
        {
            name:'acornNumbers',
            url:'games/nonrefactored/acornNumbers/acornNumbers',
            sceneName:'acorn',
            subject:'math',
            review:true
        },//34
		{
            name:'popSteroids',
            url:'games/nonrefactored/popSteroids/popSteroids',
            sceneName:'popScene',
            subject:'math',
            review:true
        },//35
		{
            name:'candyShapes',
            url:'games/nonrefactored/popSteroids/popSteroids',
            sceneName:'candy',
            subject:'math',
            review:true
        },//36
		{
            name:'featherShelter',
            url:'games/nonrefactored/featherShelter/featherShelter',
            sceneName:'feather',
            subject:'math',
            review:true
        },//37
		{
            name:'mathCircus',
            url:'games/nonrefactored/mathCircus/mathCircus',
            sceneName:'circus',
            subject:'math',
            review:true
        },//38
		{
            name:'flightoclock',
            url:'games/nonrefactored/flightoclock/flightoclock',
            sceneName:'flightoclock',
            subject:'math',
            review:true
        },//39
		{
            name:'clashCritters',
            url:'games/nonrefactored/clashCritters/clashCritters',
            sceneName:'clash',
            subject:'math',
            review:true
        },//40
		{
            name:'mathPort',
            url:'games/nonrefactored/mathPort/mathPort',
            sceneName:'port',
            subject:'math',
            review:true},//41

		{
            name:'pizzafraction',
            url:'games/nonrefactored/pizzafraction/pizzafraction',
            sceneName:'pizzafraction',
            subject:'math',
            review:true
        },//42
		{
            name:'hungryToads',
            url:'games/nonrefactored/hungryToads/hungryToads',
            sceneName:'hungry',
            subject:'math',
            review:true
        }
	]



    return games
}
